### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by nirajpatel2402** [nirajpatel2402/Android-Bootcamp-ToDoApp#1]
I am done with initial ToDoApp. Please review. /cc @codepathreview @codepath

Suggestions are welcomed!!

**Comment by nesquena** [comment]
Hi Niraj,

Looks good, and thanks for submitting your pre-work. We hope you enjoyed working on the project! Unfortunately, due to high demand this round, we are restricting participation in July to those with at least 1 year of experience after graduating with their most recent engineering degree (excluding internships). We hope you are able to participate in a future cohort though!

In the meantime, there are a lot of resources out there for people interested in learning Android and we’ve done some work to make them more accessible. We [have many online resources for learning Android](http://courses.codepath.com/snippets/intro_to_android/email_faq#heading-i-do-not-live-in-the-bay-area-can-i-take-your-classes-locally-or-remotely) including a long list of [Android resources online](http://guides.codepath.com/android/Beginning-Android-Resources#beginning-android-resources). You can also follow [us on Twitter @codepath](https://twitter.com/codepath) for news of future courses.

Hope to be able to expand our audience for future programs. Thanks for your understanding,

**Comment by nirajpatel2402** [comment]
/cc @codepathreview @codepath

Hi Nathan,

Thank you for taking the time to review my app. 

I completely respect your decision and objective opinion about required experience for the participation. After all, you are the one who know exactly what I need for the participation. With that said, I would like to request for reconsideration of my candidacy because I strongly feel that my background and past experience have prepared me for participation. I am very eager and enthusiastic about this course. I have updated my app with additional requirements and it is ready for review.

Thank you very much Nathan and I will respect any decision you make. 

Sincerely,
Niraj Patel

**Comment by nesquena** [comment]
Hi Niraj,

I appreciate the note and your interest in the course. I have added you to a waitlist for the course. In the even that you are unable to participate directly, I'd like to offer you a chance to get access to the course materials as a remote self-paced observer so you can still learn using our materials and assignments.  That way you can still hopefully benefit from them. Will follow up with you again soon.

**Comment by nirajpatel2402** [comment]
Thank you Nathan. I am hopeful to learn something from hear.
